all tests pass except for testESMP
=====================================================================
FAIL: test_ESMP_Conservative (__main__.TestESMPRegridding)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "testESMP.py", line 78, in test_ESMP_Conservative
    self.assertLess(abs(srcResult - dstResult), self.eps)
AssertionError: 0.006993480958044529 not less than 1e-10

leaving aside because this test was also failing on other platforms